<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox_task</name>
   <tag></tag>
   <elementGuidId>2e16e877-55f9-4d12-99a2-e3e234970b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='mytodos']/child::li/child::span[contains(text(),'${nomeDaTask}')]/preceding-sibling::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//ul[@id='mytodos']/child::li/child::span[contains()='${nomeDaTask}']/preceding-sibling::input</value>
   </webElementXpaths>
</WebElementEntity>
